### ISSUE TITLE
How to customize colors

### ISSUE THREAD

**Issue by iagorm** [Veriff/veriff-sample-android#24]
Hello, which class allows SDK to open with a custom theme?

EDIT: I saw the Builder method to set up a custom color is deprecated, how we can override the styles for the buttons and the blue circle?

**Comment by iagorm** [comment]
Any solution on that @madisp?

**Comment by madisp** [comment]
Hi, this is not possible at the moment. I've raised it internally and the functionality may come back in the future.

As you've noticed, the deprecated methods do nothing and they will be removed in a future release.
