### ISSUE TITLE
RuntimeException takePicture failed

### ISSUE THREAD

**Issue by iagorm** [Veriff/veriff-sample-android#28]
Hello, I got an exception, it crashed the app when trying to take a face photo, happened once, I have the stack trace to help to find error:

## Device 
Family | ONE
Model | ONE E1003 (MMB29M)
Architecture | armeabi-v7a
Battery Level | 84%
Orientation | portrait
Memory | Total: 2.8 GB / Free: 1015.0 MB
Capacity | Total: 11.5 GB / Free: 6.1 GB
Simulator | False
brand | OnePlus
charging | False
low_memory | False
manufacturer | OnePlus
online | True
screen_density | 3
screen_dpi | 480
screen_resolution | 1920x1080

## Error trace
`RuntimeException failed`

```
android.hardware.Camera in native_takePicture
android.hardware.Camera in takePicture at line 1529
android.hardware.Camera in takePicture at line 1473
mobi.lab.veriff.fragment.CameraAPI1Fragment$7 in run at line 522
android.os.Handler in handleCallback at line 739
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 148
android.app.ActivityThread in main at line 5539
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 726
com.android.internal.os.ZygoteInit in main at line 616
```

**Comment by MarkKerner** [comment]
Hi! This is a legacy camera implementation in no-video flow, which was faulty and susceptible to crashing. We released a completely new and reliable camera implementation in no-video flow today with version 2.3.5.
