### ISSUE TITLE
UI ignores document.type

### ISSUE THREAD

**Issue by domasn** [Veriff/veriff-sample-android#3]
**Same as in iOS**: https://github.com/Veriff/veriff-sample-ios/issues/2
Veriff version: `2.0.0`

When creating a session with a POST to `/sessions` we specify document type as described in the [docs](https://developers.veriff.me):
> type: (one of PASSPORT, ID_CARD, DRIVERS_LICENSE, RESIDENCE_PERMIT)
Document type

Nevertheless, after user selects country of document he is promted to select the document type:

![Screenshot 2019-03-12 at 13 46 00](https://user-images.githubusercontent.com/7569279/54197575-f5d67300-44cc-11e9-9804-995c5dda17b7.png)

This results with `/webhooks /decision` that has a `document.type` mismatching the one sent to `/session`

**Comment by MarkKerner** [comment]
Specifying the document type from API is currently not implemented on SDK-side. We will analyse this feature in next week's sprint.

**Comment by iagorm** [comment]
Is this fixed?

**Comment by madisp** [comment]
Hi, yes, this was fixed in 2.2.1. Are you on that version or later?

**Comment by iagorm** [comment]
Hello, no, I'm in the latest at moment `2.3.4`, we tested the host `/v1` in iOS and the behavior was correct, in Android showed country list.
