### ISSUE TITLE
cannot access instance field from object of type Reference: org.json.JSONObject

### ISSUE THREAD

**Issue by jrojas25** [Veriff/veriff-sample-android#33]
I'm having the following log after initializing the SDK (v.2.4.8)

`Application crashed: java.lang.VerifyError: Verifier rejected class com.veriff.sdk.internal.k$a: void com.veriff.sdk.internal.k$a.a(com.veriff.sdk.internal.k2, com.veriff.sdk.internal.i3) failed to verify: void com.veriff.sdk.internal.k$a.a(com.veriff.sdk.internal.k2, com.veriff.sdk.internal.i3): [0xE] cannot access instance field com.veriff.sdk.internal.k$b com.veriff.sdk.internal.k$a.a from object of type Reference: org.json.JSONObject (declaration of 'com.veriff.sdk.internal.k$a' appears in /data/app/com.my.app-sGVvjRQBludBoe680Wcjsg::/base.apk!classes3.dex)`

**Comment by madisp** [comment]
Hi @jrojas25 , thanks for the bug report!
This looks like it's caused by a combination of Veriff and the build tools you're using. Can you tell me, which version of Android Gradle Plugin are you currently using? It will greatly help us to pinpoint the issue.

**Comment by madisp** [comment]
Additional question, do you happen to use the New Relic Gradle plugin in your build?

**Comment by jrojas25** [comment]
Hi @madisp, we're using:
com.android.tools.build:gradle:3.5.1

and for new relic:
com.newrelic.agent.android:android-agent:5.22.0
com.newrelic.agent.android:agent-gradle-plugin:5.22.0

**Comment by madisp** [comment]
Hi @jrojas25, yup, looks like this is an issue in the New Relic Gradle plugin - https://discuss.newrelic.com/t/newrelic-bytecode-instrumentation-breaks-stripe-library/79500

We did a workaround on our end, can you try upgrading to Veriff Android SDK 2.5.0?

**Comment by jrojas25** [comment]
It started to work now with 2.5.0, thanks @madisp
