### ISSUE TITLE
Cannot run on x86 emulator

### ISSUE THREAD

**Issue by justasm** [Veriff/veriff-sample-android#5]
**Steps to reproduce**

1. Build and run project on an x86 Android emulator.

**Expected**

Sample app is installed and runs successfully.

**Actual**

Installation fails with `INSTALL_FAILED_NO_MATCHING_ABIS`.

**Analysis**

Analyzing the built APK with Android Studio's APK analyzer tool suggests that the Veriff SDK pulls in a dependency on libjingle which is only provided for the `arm64-v8a` and `armeabi-v7a` architectures. To run on an x86 emulator, a version of libjingle for the `x86` architecture needs to be included.

![Screen Shot 2019-04-18 at 17 01 55](https://user-images.githubusercontent.com/1081815/56366387-b1d93b00-61fb-11e9-858a-d772af65dd0e.png)

**Comment by madisp** [comment]
Hi, thanks for letting us know!

Your analysis is spot-on, we're not including the `x86` binaries in the SDK and we probably should. I'll let you know when there's a release out with `x86` binaries.

**Comment by madisp** [comment]
@justasm we've released 2.3.0 and it includes x86 and x86_64 ABIs of libjingle, you should be able to use emulators now.
