### ISSUE TITLE
Sample project does not compile with `minifyEnabled = true`

### ISSUE THREAD

**Issue by eligijusTrafi** [Veriff/veriff-sample-android#6]

**Comment by madisp** [comment]
Hello, thanks for the report!

Have you included the proguard rules listed in https://github.com/Veriff/veriff-sample-android#4-veriff-project-proguard-rulespro-file-contents?

If you already have them included, could you tell us how the compile fails?

**Comment by eligijusTrafi** [comment]
Yes, tried to include it, but the thing was that compile did not fail.  App crashed at runtime after opening your SDK flow. One of `org.webrtc.**` classes were missing so I added `-keep class org.webrtc.** { *; }` to our proguard-rules file and that fixed it

**Comment by eligijusTrafi** [comment]
Oh sorry, the problem about the crash that I wrote 🔝 was in our project. I couldn't test it in this sample project because of the compile fail. You could easily see the problem by changing `minifyEnabled = true` in your `gradle.build` file

**Comment by madisp** [comment]
Thanks for reporting this! We've updated both the documentation and also updated the embedded Proguard rules in Veriff SDK 2.3.2.
